import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: [
    'src/router.tsx',
    'src/routes/**/*.{ts,tsx}',
    'scripts/**/*.{mjs,ts}',
    'e2e/**/*.ts',
    'src/styles.css',
  ],
  project: ['src/**/*.{ts,tsx}', 'scripts/**/*.{mjs,ts}', 'e2e/**/*.ts'],
  ignore: [
    // Generated by TanStack Router — committed, never edited by hand.
    'src/routeTree.gen.ts',
    // shadcn primitives reserved for Phase C / upcoming console surfaces
    'src/components/ui/input.tsx',
    'src/components/ui/scroll-area.tsx',
    'src/components/ui/sheet.tsx',
    'src/components/ui/tabs.tsx',
    'src/components/ui/tooltip.tsx',
  ],
  ignoreDependencies: [
    // Imported from CSS (`@import "tailwindcss"`), not JS.
    'tailwindcss',
    // Loaded via `nitro/vite` plugin subpath in vite.config.ts.
    'nitro',
    // Invoked as a CLI binary from scripts/ci/verify.mjs.
    'madge',
    // Transitive helper pulled by shadcn CLI output.
    'tslib',
  ],
  vite: true,
};

export default config;
